### PR TITLE
Compatibility of base32 padding

### LINKED ISSUE #3: Base32 padding causes QR code to not work for Google Authenticator
Example QR code data. This will work on Microsoft Authenticator but _not_ Google Authenticator
`otpauth://totp/issuer:martin?secret=MNRWIZLGMU4WMZTEMNSDEZBVG4YWCZLCHEYTCMRZMRRDKNZWGFSTMOJXGIYDGZRTHA3GGYZQMRSGGNTEHE4DKNZQHFRTSNRUGA4WINA%3D&issuer=issuer&algorithm=SHA1`

And here's a fixed example. This will work on both Microsoft Authenticator and Google Authenticator
`otpauth://totp/issuer:martin?secret=MNRWIZLGMU4WMZTEMNSDEZBVG4YWCZLCHEYTCMRZMRRDKNZWGFSTMOJXGIYDGZRTHA3GGYZQMRSGGNTEHE4DKNZQHFRTSNRUGA4WINA&issuer=issuer&algorithm=SHA1`

Note the `%3D` at the end of the secret that is removed.

My work around at the moment is to just have this `TOTP.Key.toString key |> String.replace "%3D" ""` but maybe the base3d secret padding changes based on secret length and this work around won't work for other users.

### PR DESCRIPTION
**Pull request by choonkeat**
Fixes #3 

After [some research](https://chatgpt.com/share/67ba8d77-1a0c-8008-8c45-046c388606af) I conclude that

1. elm-totp should strip off any trailing = from [base32 encoded] secrets by default.
2. decoding function can be made tolerant of both padded and unpadded input, so that secrets from other sources (whether or not they have =) are accepted.

### CODE REVIEW

File: src/TOTP/Base32String.elm [hunk 1]
```diff
@@ -14,17 +14,53 @@ type Base32String
...
-    Base32.decode s
+    let
+        padLength =
+            (8 - modBy 8 (String.length s)) |> modBy 8
+
+        padded =
+            s ++ String.repeat padLength "="
+    in
+    Base32.decode padded
         |> Result.map Bytes.Extra.fromByteValues
```
Comment (choonkeat) [inline src/TOTP/Base32String.elm:64]: gist of the fix

File: tests/Base32StringTest.elm [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+    describe "Base32String"
+        [ fuzz Fuzz.string "stringToBase32 and bytesFromBase32 are reversible for any string" <|
+            \str ->
+                str
+                    |> stringToBase32
+                    |> Result.andThen bytesFromBase32
+                    |> Result.map Bytes.Extra.toByteValues
+                    |> Result.map String.Extra.fromCodePoints
+                    |> Expect.equal (Ok str)
+        ]
```
Comment (choonkeat) [inline tests/Base32StringTest.elm:22]: added round-trip test with fuzzing

File: package.json [hunk 3]
```diff
@@ -0,0 +1,8 @@
+{
+  "name": "recreated-from-lock",
+  "version": "1.0.0",
+  "dependencies": {},
+  "devDependencies": {
+    "elm-verify-examples": "5.2.0"
+  }
+}
```
Comment (choonkeat) [inline package.json:8]: off topic but I realise this file is missing. reconstructed with https://gist.github.com/choonkeat/5a7a6edd7137c3aeac2c3023aa60b90a

**Comment by MartinSStewart** [comment]
I tested out your changes and removed my work around and everything appears to work. Thanks for the fix!

**Comment by choonkeat** [comment]
released as 1.1.2 with your fix on the package description too ac5bd3a 🙇
